#!/bin/sh
### BEGIN INIT INFO
# Provides:          api-service
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Start API server with static IP
### END INIT INFO

case "$1" in
  start)
    echo "Esperando interfaz eth0..."
    i=0
    while [ $i -lt 10 ]; do
        if ip link show eth0 | grep -q "state UP"; then
            break
        fi
        sleep 1
        i=$((i+1))
    done

    echo "Fijando IP estática en eth0"
    ifconfig eth0 192.168.0.150 netmask 255.255.255.0 up
    route add default gw 192.168.0.1

    echo "Lanzando API Flask..."
    nohup python3 /usr/bin/API.py > /tmp/api.log 2>&1 &
    ;;
  stop)
    echo "Deteniendo API Flask"
    killall python3
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Uso: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

